services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: app
    restart: always
    command: 'uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    ports:
      - '8000:8000'
    networks:
      - app-net
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: task_psgr
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-net


networks:
  app-net:
    driver: bridge

volumes:
  postgres: