"""Add relationship between User and Task

Revision ID: a4fa866af16f
Revises: 14fbbd0ea60e
Create Date: 2025-05-07 12:47:47.877006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4fa866af16f'
down_revision: Union[str, None] = '14fbbd0ea60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
